import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "./providers";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "library management system",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <main>
          <Providers>
            {children}
          </Providers>
        </main>
      </body>
    </html>

  );
}
